//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace CampfirePlannerPlanner.ASP.Net.HomePage {
    
    
    public partial class HomePage {
        
        /// <summary>
<<<<<<< HEAD
        /// cbl_categories control.
=======
        /// GridView1 control.
>>>>>>> b7e52a6c4944f56bcc9f292ee6d861c6496da635
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
<<<<<<< HEAD
        protected global::System.Web.UI.WebControls.CheckBoxList cbl_categories;
=======
        protected global::System.Web.UI.WebControls.GridView GridView1;
        
        /// <summary>
        /// lbl_userid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lbl_userid;
>>>>>>> b7e52a6c4944f56bcc9f292ee6d861c6496da635
    }
}
